---
# tasks file for vzell.yum-gnome

# https://support.oracle.com/epmos/faces/DocumentDisplay?id=2153562.1
- name: Install the 'Gnome desktop' environment group
  yum:
    name: "@^Server with GUI"
    state: present

- name: Use systemctl command to enable GUI on system start
  command: systemctl set-default graphical.target
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version > '6'
  register: enable_gui

- name: Debug enabling GUI on system start
  debug: 
    var: enable_gui.stdout_lines
  when: enable_gui is changed

- name: Unconditionally reboot the machine to GUI mode
  reboot:
