---
# tasks file for vzell.yum-gnome

# https://support.oracle.com/epmos/faces/DocumentDisplay?id=2153562.1
- name: Install the 'Gnome desktop' environment group
  yum:
    name: "@^graphical-server-environment"
    state: present
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '7'

- name: Install the 'Gnome desktop' environment group
  dnf:
    name: "@graphical-server-environment"
    state: present
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version == '8'

- name: Use systemctl command to enable GUI on system start
  command: systemctl set-default graphical.target
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version > '6'
  register: enable_gui

- name: Debug enabling GUI on system start
  debug: 
    var: enable_gui.stdout_lines
  when: enable_gui is changed

- name: Use systemctl command to start GUI
  command: systemctl isolate graphical.target
  when: ansible_os_family == 'RedHat' and ansible_distribution_major_version > '6'

